version: '2.1'

volumes:
  db-data:
  vendor:
  var:


services:
  mysql:
    image: mysql:5
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    restart: always
  prestashop-git:
    build:
      dockerfile: .docker/Dockerfile
      context: .
    environment:
      PS_INSTALL_AUTO: 1
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      DB_SERVER: mysql
      PS_DOMAIN: localhost:8001
      PS_FOLDER_INSTALL: install-dev
      PS_FOLDER_ADMIN: admin-dev
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html/:delegated

# FIRST INSTALL DEPENDENCIES:
# composer install --ignore-platform-reqs
